# Table segmentation pipeline configuration

# Random seed for reproducibility
seed: 42

# Dataset paths
depth_dir: "./data/train/depth"
label_dir: "./data/train/labels"
test_depth_dir: "./data/test/depth"
test_label_dir: "./data/test/labels"

# Dataset split
train_split: 0.8

# Camera intrinsics matrix (3x3)
camera_intrinsics:
  - [525.0, 0.0, 319.5]  # fx, 0, cx
  - [0.0, 525.0, 239.5]  # 0, fy, cy
  - [0.0, 0.0, 1.0]      # 0, 0, 1

# Training configuration
training:
  batch_size: 8
  num_workers: 4
  num_epochs: 50
  learning_rate: 0.001
  weight_decay: 0.0001
  momentum: 0.9
  optimizer: "adam"  # Options: "adam", "sgd"
  use_class_weights: true
  checkpoint_dir: "./checkpoints"
  save_freq: 5
  use_wandb: true
  project_name: "table_segmentation"

# Evaluation configuration
evaluation:
  batch_size: 16
  num_workers: 4
  output_dir: "./results"
